// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ntify/extended_metadata_stuff.proto

package com.spotifyxp.protogens;

public final class ExtendedMetadataStuff {
  private ExtendedMetadataStuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OnPlatformReputationTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spotifyxp.extended_metadata.OnPlatformReputationTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 monthlyListeners = 4;</code>
     * @return The monthlyListeners.
     */
    int getMonthlyListeners();
  }
  /**
   * Protobuf type {@code spotifyxp.extended_metadata.OnPlatformReputationTrait}
   */
  public static final class OnPlatformReputationTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spotifyxp.extended_metadata.OnPlatformReputationTrait)
      OnPlatformReputationTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OnPlatformReputationTrait.newBuilder() to construct.
    private OnPlatformReputationTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OnPlatformReputationTrait() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OnPlatformReputationTrait();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spotifyxp.protogens.ExtendedMetadataStuff.internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spotifyxp.protogens.ExtendedMetadataStuff.internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.class, com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.Builder.class);
    }

    public static final int MONTHLYLISTENERS_FIELD_NUMBER = 4;
    private int monthlyListeners_ = 0;
    /**
     * <code>int32 monthlyListeners = 4;</code>
     * @return The monthlyListeners.
     */
    @java.lang.Override
    public int getMonthlyListeners() {
      return monthlyListeners_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (monthlyListeners_ != 0) {
        output.writeInt32(4, monthlyListeners_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (monthlyListeners_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, monthlyListeners_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait)) {
        return super.equals(obj);
      }
      com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait other = (com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait) obj;

      if (getMonthlyListeners()
          != other.getMonthlyListeners()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONTHLYLISTENERS_FIELD_NUMBER;
      hash = (53 * hash) + getMonthlyListeners();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spotifyxp.extended_metadata.OnPlatformReputationTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spotifyxp.extended_metadata.OnPlatformReputationTrait)
        com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spotifyxp.protogens.ExtendedMetadataStuff.internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spotifyxp.protogens.ExtendedMetadataStuff.internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.class, com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.Builder.class);
      }

      // Construct using com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        monthlyListeners_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spotifyxp.protogens.ExtendedMetadataStuff.internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_descriptor;
      }

      @java.lang.Override
      public com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait getDefaultInstanceForType() {
        return com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.getDefaultInstance();
      }

      @java.lang.Override
      public com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait build() {
        com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait buildPartial() {
        com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait result = new com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.monthlyListeners_ = monthlyListeners_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait) {
          return mergeFrom((com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait other) {
        if (other == com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait.getDefaultInstance()) return this;
        if (other.getMonthlyListeners() != 0) {
          setMonthlyListeners(other.getMonthlyListeners());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 32: {
                monthlyListeners_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int monthlyListeners_ ;
      /**
       * <code>int32 monthlyListeners = 4;</code>
       * @return The monthlyListeners.
       */
      @java.lang.Override
      public int getMonthlyListeners() {
        return monthlyListeners_;
      }
      /**
       * <code>int32 monthlyListeners = 4;</code>
       * @param value The monthlyListeners to set.
       * @return This builder for chaining.
       */
      public Builder setMonthlyListeners(int value) {

        monthlyListeners_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 monthlyListeners = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonthlyListeners() {
        bitField0_ = (bitField0_ & ~0x00000001);
        monthlyListeners_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spotifyxp.extended_metadata.OnPlatformReputationTrait)
    }

    // @@protoc_insertion_point(class_scope:spotifyxp.extended_metadata.OnPlatformReputationTrait)
    private static final com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait();
    }

    public static com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OnPlatformReputationTrait>
        PARSER = new com.google.protobuf.AbstractParser<OnPlatformReputationTrait>() {
      @java.lang.Override
      public OnPlatformReputationTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OnPlatformReputationTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OnPlatformReputationTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.spotifyxp.protogens.ExtendedMetadataStuff.OnPlatformReputationTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#ntify/extended_metadata_stuff.proto\022\033s" +
      "potifyxp.extended_metadata\"5\n\031OnPlatform" +
      "ReputationTrait\022\030\n\020monthlyListeners\030\004 \001(" +
      "\005B\031\n\027com.spotifyxp.protogensb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spotifyxp_extended_metadata_OnPlatformReputationTrait_descriptor,
        new java.lang.String[] { "MonthlyListeners", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
