name: Nightly

on:
  push:
    branches:
      - developer
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Set up maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: '8'
      - name: Clone Repository
        run: git clone --branch developer --recursive https://github.com/SpotifyXP/SpotifyXP
      - name: Run init.py
        working-directory: ./SpotifyXP
        run: python3 init.py
      - name: Build with Maven
        run: mvn --batch-mode -f SpotifyXP/pom.xml --update-snapshots package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build
          path: /home/grunner/actions-runner/_work/SpotifyXP/SpotifyXP/SpotifyXP/target/SpotifyXP.jar
